using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CommonServices.Model
{
    public class Booking
    {
        [Key]
        public int BookingId { get; set; }

        //add ScheduleId refrence
        [ForeignKey("ScheduleId")]
        public int ScheduleId { get; set; }
        public virtual Schedule Schedule { get; set; }

        //add UserId refrence
        [ForeignKey("UserId")]
        public int UserId { get; set; }
        public virtual User User { get; set; }

        //User enters the below details while booking

        public string Name { get; set; }

        [Required]
        public string Email { get; set; }

        public int NoOfSeats { get; set; }

        //PNR Number generated by us after booking
        public int? PNRNumber { get; set; }

        public virtual ICollection<PassengerDetails> PassengerDetails { get; set; }


    }

    public class PassengerDetails
    {
        
        [Key]
        public int PassengerId { get; set; }

        [ForeignKey("BookingId")]
        public int BookingId { get; set; }

        public virtual Booking Booking { get; set; }

        //each passenger details based on NoOfSeats
        public string PassengerName { get; set; }

        public string Gender { get; set; }

        public int Age { get; set; }

        public string Meal { get; set; }

        public string SeatType { get; set; }
    }
}
